mySite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('dayoff/', include('dayoff.urls')),
    path('', include('goodgames.urls'))
]

polls/urls.py
from django.urls import path

from polls import views

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:poll_id>/', views.detail, name='poll_detail'),
    path('detail/<int:poll_id>/create-comments/', views.comment, name='poll_comment'),
    path('detail/<int:poll_id>/question/', views.create_question, name='poll_question'),
    path('create/', views.create_poll, name='create_poll'),
    path('login/', views.mylogin, name='login'),
    path('logout/', views.mylogout, name='logout'),
    path('detail/<int:poll_id>/update/', views.update_poll, name='update_poll'),
    path('delete/<int:poll_id>/', views.delete_poll, name='delete_poll'),
    path('detail/<int:poll_id>/question/<int:question_id>/delete/', views.delete_question, name='delete_question'),
    path('detail/<int:poll_id>/question/<int:question_id>/choice/', views.add_choice, name='edit_choice'),
    path('detail/<int:poll_id>/question/<int:question_id>/choice/api', views.add_choice_api, name='add_choice_api'),
]

polls/models.py
from django.db import models

# Create your models here.
class Poll(models.Model):
    title = models.CharField(max_length=100)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    del_flag = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Question(models.Model):
    text = models.TextField()
    SINGLE = '01'
    MULTIPLE = '02'
    TYPES = (
        (SINGLE, 'Single answer'),
        (MULTIPLE, 'Multiple answer')
    )
    type = models.CharField(max_length=2, choices=TYPES, default='01')
    poll = models.ForeignKey(Poll, on_delete=models.PROTECT)

    def __str__(self):
        return '(%s) %s' % (self.poll.title, self.text)


class Choice(models.Model):
    text = models.CharField(max_length=100)
    value = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.PROTECT)

    def __str__(self):
        return '(%s) %s' % (self.question.text, self.text)


class Answer(models.Model):
    choice = models.OneToOneField(Choice, on_delete=models.PROTECT)
    question = models.ForeignKey(Question, on_delete=models.PROTECT)

class Comment(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    email = models.EmailField()
    tel = models.CharField(max_length=10)

polls/forms.py
from datetime import datetime
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
from django.core.validators import validate_integer
from django.utils.timezone import now

from polls.models import Poll, Question, Comment, Choice


def validate_even(value):
    if value % 2 != 0:
        raise ValidationError('%(value)s ไม่ใช่เลขคู่', params={'value': value})


class PollForm(forms.Form):
    title = forms.CharField(label="ชื่อโพล", max_length=100, required=True)
    email = forms.CharField(validators=[validators.validate_email])
    no_questions = forms.IntegerField(label="จำนวนคำถาม", min_value=0, max_value=10,
                                      required=True, validators=[validate_even])
    start_date = forms.DateField(required=False)
    end_date = forms.DateField(required=False)

    # def clean_title(self):
    #     data = self.cleaned_data['title']
    #
    #     if "ไอทีหมีแพนด้า" not in data:
    #         raise forms.ValidationError("คุณลืมชื่อคณะ")
    #
    #     return data
    #
    # def clean(self):
    #     cleaned_data = super().clean()
    #     start = cleaned_data.get('start_date')
    #     end = cleaned_data.get('end_date')
    #
    #     if start and not end:
    #         # raise forms.ValidationError("โปรดเลือกวันสิ้นสุด")
    #         self.add_error('end_date', "โปรดเลือกวันสิ้นสุด")
    #     elif not start and end:
    #         # raise forms.ValidationError("โปรดเลือกวันเริ่มต้น")
    #         self.add_error('start_date', "โปรดเลือกวันเริ่มต้น")


class QuestionForm(forms.ModelForm):
    question_id = forms.IntegerField(required=False, widget=forms.HiddenInput)

    class Meta:
        model = Question
        exclude = ['poll']

        widgets = {
            'text': forms.TextInput(attrs={'class': 'form-control'}),
            'type': forms.Select(attrs={'class': 'form-control'}),
        }


class QuestionModelForm(forms.Form):
    question = forms.CharField(widget=forms.Textarea)


class PollModelForm(forms.ModelForm):
    class Meta:
        model = Poll
        exclude = ['del_flag']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'start_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'end_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        }

    # def clean_title(self):
    #     data = self.cleaned_data['title']
    #
    #     if "ไอทีหมีแพนด้า" not in data:
    #         raise forms.ValidationError("คุณลืมชื่อคณะ")
    #
    #     return data
    #
    # def clean(self):
    #     cleaned_data = super().clean()
    #     start = cleaned_data.get('start_date')
    #     end = cleaned_data.get('end_date')
    #
    #     if start and not end:
    #         # raise forms.ValidationError("โปรดเลือกวันสิ้นสุด")
    #         self.add_error('end_date', "โปรดเลือกวันสิ้นสุด")
    #     elif not start and end:
    #         # raise forms.ValidationError("โปรดเลือกวันเริ่มต้น")
    #         self.add_error('start_date', "โปรดเลือกวันเริ่มต้น")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['title', 'body', 'email', 'tel']

    # title = forms.CharField(max_length=100, required=True)
    # body = forms.CharField(max_length=500, required=True)
    # email = forms.EmailField(validators=[validators.validate_email])
    # tel = forms.IntegerField(min_value=10, max_value=10)

    # def clean_title(self):
    #     data = self.cleaned_data['title']
    #
    #     if not data:
    #         raise forms.ValidationError("ต้องกรอก email หรือ Mobile Number")
    #
    #     return data

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        mobile = cleaned_data.get('tel')

        if not email and not mobile:
            self.add_error('tel', "ต้องกรอก email หรือ Mobile Number")
            # raise forms.ValidationError("โปรดเลือกวันสิ้นสุด")
        try:
            int(mobile)
        except:
            self.add_error('tel', "หมายเลขโทรศัพท์ต้องเป็นตัวเลขเท่านั้น")
        if len(mobile) < 10:
            # raise forms.ValidationError("โปรดเลือกวันเริ่มต้น")
            self.add_error('tel', "หมายเลขโทรศัพท์ต้องมี 10 หลัก")
        # elif not validators.validate_email(email):
        #     self.add_error('email', "Email a valid email address")


# class ContactForm(forms.Form):
#     subject = forms.CharField(max_length=100)
#     message = forms.CharField()
#     sender = forms.EmailField()
#     recipients =

class ChoiceModelForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = '__all__'


class CreateQuestion(forms.Form):
    text = forms.CharField(widget=forms.Textarea)
    value = forms.IntegerField(max_value=1)

polls/views.py
import os
import json

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.forms import formset_factory
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect

from .forms import PollForm, PollModelForm, QuestionForm, CommentForm, CreateQuestion, QuestionModelForm, \
    ChoiceModelForm
from polls.models import Poll, Question, Answer, Choice


# Create your views here.
def index(request):
    poll_list = Poll.objects.all()

    for poll in poll_list:
        question_count = Question.objects.filter(poll_id=poll.id).count()
        poll.question_count = question_count

    context = {
        'page_title': "My Polls",
        'poll_list': poll_list
    }
    return render(request, template_name='polls/index.html', context=context)


@login_required
@permission_required('polls.view_poll')
def detail(request, poll_id):
    poll = Poll.objects.get(pk=poll_id)
    for question in poll.question_set.all():
        name = 'choice' + str(question.id)
        choice_id = request.GET.get(name)
        if choice_id:
            try:
                ans = Answer.objects.get(question_id=question.id)
                ans.choice_id = choice_id
            except Answer.DoesNotExist:
                Answer.objects.create(
                    choice_id=choice_id,
                    question_id=question.id
                )

    return render(request, 'polls/detail.html', {'poll': poll})


# Poll CRUD Function #

def create_poll(request):
    context = {}
    ques = 0
    QuestionFormSet = formset_factory(QuestionForm, extra=2)
    if request.method == 'POST':
        form = PollModelForm(request.POST)

        formset = QuestionFormSet(request.POST)
        if form.is_valid():
            poll = form.save()
            if formset.is_valid():
                for question_form in formset:
                    Question.objects.create(
                        text=question_form.cleaned_data.get('text'),
                        type=question_form.cleaned_data.get('type'),
                        poll_id=poll.id
                    )
                    # ques += 1
                context['success'] = "Poll %s is created successfully!" % poll.title
                # ques = 0
            # poll = Poll.objects.create(
            #     title=form.cleaned_data.get('title'),
            #     start_date=form.cleaned_data.get('start_date'),
            #     end_date=form.cleaned_data.get('end_date'),

            # )
            # for i in range(1, form.cleaned_data.get('no_questions')+1):
            #     Question.objects.create(
            #         text='QQQQ'+str(i),
            #         type='01',
            #         poll=poll
            #     )
    else:
        form = PollModelForm()
        formset = QuestionFormSet()

    context['form'] = form
    context['formset'] = formset

    return render(request, 'polls/create_poll.html', context=context)


@login_required
def update_poll(request, poll_id):
    poll = Poll.objects.get(id=poll_id)
    QuestionFormSet = formset_factory(QuestionForm, extra=2)
    context = {'poll': poll}

    if request.method == 'POST':
        form = PollModelForm(request.POST)
        formset = QuestionFormSet(request.POST)

        if form.is_valid():
            # form.save()
            if formset.is_valid():
                for question_form in formset:
                    if question_form.cleaned_data.get('question_id'):
                        question = Question.objects.get(id=question_form.cleaned_data.get('question_id'))

                        if question:
                            question.text = question_form.cleaned_data.get('text')
                            question.type = question_form.cleaned_data.get('type')
                            question.save()
                    else:
                        if question_form.cleaned_data.get('text'):
                            Question.objects.create(
                                text=question_form.cleaned_data.get('text'),
                                type=question_form.cleaned_data.get('type'),
                                poll_id=poll.id
                            )
            context['success'] = "Saved successful"
            formset = QuestionFormSet(initial=[{'text': i.text, 'type': i.type, 'question_id': i.id}
                                               for i in poll.question_set.all()])

    else:
        form = PollModelForm(instance=poll)
        data = []
        for question in poll.question_set.all():
            data.append(
                {
                    'text': question.text,
                    'type': question.type,
                    'question_id': question.id
                }
            )
        formset = QuestionFormSet(initial=data)

    context['form'] = form
    context['formset'] = formset

    return render(request, 'polls/update.html', context=context)


@login_required
def delete_poll(request, poll_id):
    poll = Poll.objects.get(id=poll_id)
    context = {'poll': poll}
    if request.method == 'POST':
        # choices.delete()
        for q in poll.question_set.all():
            for c in q.choice_set.all():
                c.delete()
            q.delete()

        poll.delete()
        return redirect('index')
    else:
        return render(request, 'polls/delete_poll.html', context=context)


# Question CRUD Function #

@login_required
# CreateQuestion
def create_question(request, poll_id):
    context = {}
    ques = 0
    CreateQuestionFormSet = formset_factory(CreateQuestion, extra=2)
    if request.method == 'POST':
        form = QuestionModelForm(request.POST)

        formset = CreateQuestionFormSet(request.POST)
        if form.is_valid():
            poll = form.save()
            if formset.is_valid():
                for question_form in formset:
                    Question.objects.create(
                        text=question_form.cleaned_data.get('question'),
                        type=question_form.cleaned_data.get('type'),
                        poll_id=poll.id
                    )
                    Choice.objects.create(
                        text=question_form.cleaned_data.get('text'),
                        value=question_form.cleaned_data.get('value')
                    )
                    ques += 1
                context['success'] = "Poll %s is created successfully!" % poll.title
                ques = 0
            # poll = Poll.objects.create(
            #     title=form.cleaned_data.get('title'),
            #     start_date=form.cleaned_data.get('start_date'),
            #     end_date=form.cleaned_data.get('end_date'),

            # )
            # for i in range(1, form.cleaned_data.get('no_questions')+1):
            #     Question.objects.create(
            #         text='QQQQ'+str(i),
            #         type='01',
            #         poll=poll
            #     )
    else:
        form = QuestionModelForm()
        formset = CreateQuestionFormSet()

    context['form'] = form
    context['formset'] = formset

    return render(request, 'questions/create.html', context=context)


@login_required
def delete_question(request, poll_id, question_id):
    question = Question.objects.get(id=question_id)
    for i in question.choice_set.all():
        i.delete()
    question.delete()
    return redirect('update_poll', poll_id=poll_id)

# Choice CRUD Function #
@login_required
def add_choice(request, poll_id, question_id):
    poll = Poll.objects.get(id=poll_id)
    question = Question.objects.get(id=question_id)
    choices = [{'id': i.id, 'text': i.text, 'value': i.value, 'question': i.question_id}
               for i in question.choice_set.all()]
    context = {'poll': poll, 'question': question, 'choices': json.dumps(choices)}
    return render(request, 'choices/add.html', context=context)


@login_required
def add_choice_api(request, poll_id, question_id):
    if request.method == 'POST':
        choice_list = json.loads(request.body)
        error_message = None

        # Algorithm: Delete choices
        database_choice_list_ids = [i.id for i in Question.objects.get(pk=question_id).choice_set.all()]
        choice_list_ids = list()

        for i in choice_list:
            try:
                choice_list_ids.append(i['id'])
            except KeyError:
                pass

        for i in database_choice_list_ids:
            if i not in choice_list_ids:
                Choice.objects.get(pk=i).delete()

        # Algorithm: Validations
        for i in choice_list:
            if i['text'] == '' or i['value'] == '':
                error_message = 'Fields can\'t be left blank.'
                break
            error_message = None

        # Algorithm: Save choices
        if not error_message:
            for i in choice_list:
                try:
                    # Case: Choice already exists.
                    Choice.objects.filter(pk=i['id']).update(text=i['text'], value=i['value'])
                except KeyError:
                    # Case: Choice doesn't exist.
                    form = ChoiceModelForm({
                        'text': i['text'],
                        'value': i['value'],
                        'question': question_id
                    })
                    if form.is_valid():
                        form.save()
                    else:
                        error_message = 'Fields can\'t be left blank.'
                        break

        if not error_message:
            return JsonResponse({'message': 'success'}, status=200)
        else:
            return JsonResponse({'message': error_message}, status=400)
    return JsonResponse({'message': 'This API does not accept GET request.'}, status=405)


@login_required
@permission_required('polls.add_comment')

polls/templates/polls/comment.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create new Poll</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        .errorlist{
            color: red;
        }
    </style>
</head>
<body>
{% if success %}<p>{{ success }}</p>{% endif %}
<form method="POST" action="{% url 'poll_comment' poll_id=poll.id %}">
    {% csrf_token %}
    {{  form.as_p }}

    <hr/>
{#    <h2>Add question(s)</h2>#}
{#    <table>#}
{#        {{ formset }}#}
{#    </table>#}
    <input type="submit" value="Comment">
</form>

<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

polls/templates/polls/create.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create new Poll</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        .errorlist{
            color: red;
        }
    </style>
</head>
<body>
{% if success %}<p>{{ success }}</p>{% endif %}
<form method="POST" action="{% url 'create_poll' %}">
    {% csrf_token %}
    {{  form.as_p }}
{#    <table border="1">#}
{#        {%  if form.non_field_errors %}#}
{#            <p>#}
{#                {{ form.non_field_errors }}#}
{#            </p>#}
{#        {% endif %}#}
{#        <tr>#}
{#            <td><label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label></td>#}
{#            <td>{{ form.title.errors }}{{ form.title }}</td>#}
{#            <td><label for="{{ form.no_questions.id_for_label }}">{{ form.no_questions.label }}</label></td>#}
{#            <td>{{ form.no_questions.errors }}{{ form.no_questions }}</td>#}
{#        </tr>#}
{#        <tr>#}
{#            <td><label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label></td>#}
{#            <td>{{ form.email.errors }}{{ form.email }}</td>#}
{#        </tr>#}
{#        <tr>#}
{#            <td><label for="{{ form.start_date.id_for_label }}">{{ form.start_date.label }}</label></td>#}
{#            <td>{{ form.start_date.errors }}{{ form.start_date }}</td>#}
{#            <td><label for="{{ form.end_date.id_for_label }}">{{ form.end_date.label }}</label></td>#}
{#            <td>{{ form.end_date.errors }}{{ form.end_date }}</td>#}
{#        </tr>#}
{#    </table>#}
    <hr/>
    <h2>Add question(s)</h2>
    <table>
        {{ formset }}
    </table>
    <input type="submit" value="Create">
</form>

<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

polls/templates/polls/create_poll.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create new Poll</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        .errorlist{
            color: red;
        }
    </style>
</head>
<body>
{% if success %}<p>{{ success }}</p>{% endif %}
<form method="POST" action="{% url 'create_poll' %}">
    {% csrf_token %}
    {{  form.as_p }}
{#    <table border="1">#}
{#        {%  if form.non_field_errors %}#}
{#            <p>#}
{#                {{ form.non_field_errors }}#}
{#            </p>#}
{#        {% endif %}#}
{#        <tr>#}
{#            <td><label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label></td>#}
{#            <td>{{ form.title.errors }}{{ form.title }}</td>#}
{#            <td><label for="{{ form.no_questions.id_for_label }}">{{ form.no_questions.label }}</label></td>#}
{#            <td>{{ form.no_questions.errors }}{{ form.no_questions }}</td>#}
{#        </tr>#}
{#        <tr>#}
{#            <td><label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label></td>#}
{#            <td>{{ form.email.errors }}{{ form.email }}</td>#}
{#        </tr>#}
{#        <tr>#}
{#            <td><label for="{{ form.start_date.id_for_label }}">{{ form.start_date.label }}</label></td>#}
{#            <td>{{ form.start_date.errors }}{{ form.start_date }}</td>#}
{#            <td><label for="{{ form.end_date.id_for_label }}">{{ form.end_date.label }}</label></td>#}
{#            <td>{{ form.end_date.errors }}{{ form.end_date }}</td>#}
{#        </tr>#}
{#    </table>#}
    <hr/>
    <h2>Add question(s)</h2>
    <table>
        {{ formset }}
    </table>
    <input type="submit" value="Create">
</form>

<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

polls/templates/polls/create_question.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Question</title>
</head>
<body>

<div class="container">
    <table>
        {{ form.as_p }}
        {{ formset }}
    </table>

    <form id="contact" action="" method="post">

        <h2>Edit Choices</h2>
{#        <h3>{{ question.text }}</h3>#}
{#        {% for choice in choices %}#}
{#            <fieldset class="row" style="text-align: center">#}
{#                <input class="col" style="width: 49%;" type="text" tabindex="1" value="{{ choice.text }}">#}
{#                <input class="col" style="width: 49%;" type="text" tabindex="1" value="{{ choice.value }}">#}
{#            </fieldset>#}
{#        {% endfor %}#}
        <fieldset>
            <input placeholder="Your name" type="text" tabindex="1" required autofocus>
        </fieldset>
        <fieldset>
            <input placeholder="Your Email Address" type="email" tabindex="2" required>
        </fieldset>
        <fieldset>
            <input placeholder="Your Phone Number (optional)" type="tel" tabindex="3" required>
        </fieldset>
        <fieldset>
            <input placeholder="Your Web Site (optional)" type="url" tabindex="4" required>
        </fieldset>
        <fieldset>
            <textarea placeholder="Type your message here...." tabindex="5" required></textarea>
        </fieldset>
        <fieldset>
            <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>
        </fieldset>
        <p class="copyright">Designed by <a href="https://colorlib.com" target="_blank" title="Colorlib">Colorlib</a></p>
    </form>
</div>

<style>
    @import url(https://fonts.googleapis.com/css?family=Roboto:400,300,600,400italic);
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        -webkit-font-smoothing: antialiased;
        -moz-font-smoothing: antialiased;
        -o-font-smoothing: antialiased;
        font-smoothing: antialiased;
        text-rendering: optimizeLegibility;
    }

    body {
        font-family: "Roboto", Helvetica, Arial, sans-serif;
        font-weight: 100;
        font-size: 12px;
        line-height: 30px;
        color: #777;
        background: #4CAF50;
    }

    .container {
        max-width: 600px;
        width: 100%;
        margin: 0 auto;
        position: relative;
    }

    #contact input[type="text"],
    #contact input[type="email"],
    #contact input[type="tel"],
    #contact input[type="url"],
    #contact textarea,
    #contact button[type="submit"] {
        font: 400 12px/16px "Roboto", Helvetica, Arial, sans-serif;
    }

    #contact {
        background: #F9F9F9;
        padding: 25px;
        margin: 150px 0;
        box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
    }

    #contact h2 {
        display: block;
        font-size: 40px;
        font-weight: 300;
        margin-bottom: 10px;
    }

    #contact h3 {
        display: block;
        font-size: 30px;
        font-weight: 300;
        margin-bottom: 10px;
    }

    #contact h4 {
        margin: 5px 0 15px;
        display: block;
        font-size: 13px;
        font-weight: 400;
    }

    fieldset {
        border: medium none !important;
        margin: 0 0 10px;
        min-width: 100%;
        padding: 0;
        width: 100%;
    }

    #contact input[type="text"],
    #contact input[type="email"],
    #contact input[type="tel"],
    #contact input[type="url"],
    #contact textarea {
        width: 100%;
        border: 1px solid #ccc;
        background: #FFF;
        margin: 0 0 5px;
        padding: 10px;
    }

    #contact input[type="text"]:hover,
    #contact input[type="email"]:hover,
    #contact input[type="tel"]:hover,
    #contact input[type="url"]:hover,
    #contact textarea:hover {
        -webkit-transition: border-color 0.3s ease-in-out;
        -moz-transition: border-color 0.3s ease-in-out;
        transition: border-color 0.3s ease-in-out;
        border: 1px solid #aaa;
    }

    #contact textarea {
        height: 100px;
        max-width: 100%;
        resize: none;
    }

    #contact button[type="submit"] {
        cursor: pointer;
        width: 100%;
        border: none;
        background: #4CAF50;
        color: #FFF;
        margin: 0 0 5px;
        padding: 10px;
        font-size: 15px;
    }

    #contact button[type="submit"]:hover {
        background: #43A047;
        -webkit-transition: background 0.3s ease-in-out;
        -moz-transition: background 0.3s ease-in-out;
        transition: background-color 0.3s ease-in-out;
    }

    #contact button[type="submit"]:active {
        box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.5);
    }

    .copyright {
        text-align: center;
    }

    #contact input:focus,
    #contact textarea:focus {
        outline: 0;
        border: 1px solid #aaa;
    }

    ::-webkit-input-placeholder {
        color: #888;
    }

    :-moz-placeholder {
        color: #888;
    }

    ::-moz-placeholder {
        color: #888;
    }

    :-ms-input-placeholder {
        color: #888;
    }
</style>
</body>
</html>

polls/templates/polls/delete_poll.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body onload="load()">

<form method="POST" name="deleteForm" action="{% url 'delete_poll' poll.id %}">
    {% csrf_token %}
</form>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
<script>
    function load() {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.value) {
                Swal.fire(
                    'Deleted!',
                    'Your file has been deleted.',
                    'success'
                )
                document.deleteForm.submit();
            }
        })
    }
</script>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My poll page</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<div class="container-fluid">
    <h1>{{ page_title }}</h1>

    <div class="card">
        <div class="card-header">
            <b style="font-size: 24px;">Poll List</b>
            {% if user.is_authenticated %}
                <div class="float-right">
                    {% if perms.polls.add_poll %}
                        <a href="{% url 'create_poll' %}" class="btn btn-success">CREATE NEW POLL</a>
                    {% endif %}
                    <a href="{% url 'logout' %}" class="btn btn-danger">LOGOUT</a>
                </div>
            {% else %}
                <div class="float-right">
                    <a href="{% url 'login' %}" class="btn btn-success">LOGIN</a>
                </div>
            {% endif %}
        </div>
        <div class="row card-body">
            <ul class="list-group col-8">
                {% for poll in poll_list %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        {{ poll.id }}. {{ poll.title }} ({{ poll.question_count }} คำถาม)
                        {% if user.is_authenticated %}
                            <div>
                                <a href="{% url 'update_poll' poll_id=poll.id %}" class="badge badge-success badge-pill">update</a>
                                <a href="{% url 'poll_detail' poll_id=poll.id %}" class="badge badge-primary badge-pill">detail</a>
                                <a href="{% url 'delete_poll' poll_id=poll.id %}" class="badge badge-danger badge-pill">delete</a>
                            </div>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
            <img class="col-4" style="width: auto; height: 150px" src="{% static 'polls/images/poll-hands1.jpg' %}"
                 alt="">
        </div>
    </div>
</div>

<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>