dayoff/urls.py
from django.urls import path

from dayoff import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create-dayoff'),
    path('login/', views.myLogin, name='login'),
    path('logout/', views.myLogout, name='logout'),
]

mySite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('dayoff/', include('dayoff.urls')),
    path('', include('goodgames.urls'))
]

polls/urls.py
from django.urls import path

from polls import views

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:poll_id>/', views.detail, name='poll_detail'),
    path('detail/<int:poll_id>/create-comments/', views.comment, name='poll_comment'),
    path('detail/<int:poll_id>/question/', views.create_question, name='poll_question'),
    path('create/', views.create_poll, name='create_poll'),
    path('login/', views.mylogin, name='login'),
    path('logout/', views.mylogout, name='logout'),
    path('detail/<int:poll_id>/update/', views.update_poll, name='update_poll'),
    path('delete/<int:poll_id>/', views.delete_poll, name='delete_poll'),
    path('detail/<int:poll_id>/question/<int:question_id>/delete/', views.delete_question, name='delete_question'),
    path('detail/<int:poll_id>/question/<int:question_id>/choice/', views.add_choice, name='edit_choice'),
    path('detail/<int:poll_id>/question/<int:question_id>/choice/api', views.add_choice_api, name='add_choice_api'),
]

dayoff/models.py
from django.db import models
from django.contrib.auth.models import User, Permission, Group

# Create your models here.

class DayOff(models.Model):
    TYPE_CHOICES = (
        ('01', 'ลากิจ'),
        ('02', 'ลาป่วย')
    )

    APPROVE_STATUS_CHOICES = (
        (0, 'ไม่อนุมัติ'),
        (1, 'อนุมัติ'),
        (2, 'รอการอนุมัติ')
    )

    reason = models.TextField(null=False, blank=False)
    type = models.CharField(max_length=2, choices=TYPE_CHOICES, null=False, blank=False)
    date_start = models.DateField(null=False, blank=False)
    date_end = models.DateField(null=False, blank=False)
    approve_status = models.IntegerField(choices=APPROVE_STATUS_CHOICES, default=2)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

dayoff/forms.py
"""
    `forms.py`
    Contains classes to create forms
"""

from django import forms
from django.core.exceptions import ValidationError

from dayoff.models import DayOff

import datetime

class DayOffForm(forms.ModelForm):
    class Meta:
        model = DayOff
        exclude = ['approve_status', 'created_by']
        widgets = {
            'reason': forms.Textarea(attrs={'class': 'form-control'}),
            'type': forms.Select(attrs={'class': 'form-control'}),
            'date_start': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'date_end': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        }

    error = None

    def clean(self):
        data = super().clean()

        start = data.get('date_start')
        end = data.get('date_end')

        if start > end:
            self.error = 'วัน - เวลาไม่ถูกต้อง'
            raise ValidationError('')
        elif start < datetime.datetime.now().date():
            self.error = 'ไม่สามารถเลือกวันในอดีตได้'
            raise ValidationError('')

dayoff/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from dayoff.models import DayOff
from dayoff.forms import DayOffForm

# Create your views here.

def index(request):
    context = {
    }

    try:
        context['dayoff_list'] = DayOff.objects.all().filter(created_by=User.objects.get(username=request.user.username))
        context['user'] = User.objects.get(username=request.user.username)
    except:
        context['dayoff_list'] = None

    return render(request, template_name='dayoff/index.html', context=context)

def create(request):
    context = {}

    if request.method == 'POST':
        form = DayOffForm(request.POST)
        if form.is_valid():
            DayOff.objects.create(
                reason=form.cleaned_data.get('reason'),
                type=form.cleaned_data.get('type'),
                date_start=form.cleaned_data.get('date_start'),
                date_end=form.cleaned_data.get('date_end'),
                approve_status=2,
                created_by=User.objects.get(username=request.user.username)
            )
            context['success'] = 'Request successfully submitted'

            form = DayOffForm()
    else:
        form = DayOffForm()

    context['form'] = form
    context['error'] = form.error

    return render(request, template_name='dayoff/create.html', context=context)

def myLogin(request):
    context = {}

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user:
            login(request, user)

            next_url = request.POST.get('next_url')
            if next_url:
                return redirect(next_url)
            else:
                return redirect('index')

        else:
            context['username'] = username
            context['password'] = password
            context['error'] = 'Wrong username or password'

    next_url = request.GET.get('next')
    if next_url:
        context['next_url'] = next_url

    return render(request, 'polls/login.html', context=context)

def myLogout(request):
    logout(request)
    return redirect('index')

dayoff/templates/dayoff/create.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Day Off Request</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
</head>
<body>
<div class="container">
    <h1 class="center title">แบบฟอร์มขอลางาน</h1>

    {% if error %}
        <div class="alert alert-danger center narrow">
            {{ error }}
        </div>
    {% endif %}

    {% if success %}
        <div class="alert alert-success center narrow">
            {{ success }}
        </div>
    {% endif %}

    <form
            class="create jumbotron narrow"
            method="POST"
            action="{% url 'create-dayoff' %}"
    >
        {% csrf_token %}

        <div class="form-group">
            <p class="text-left">เนื่องจาก</p>
            {{ form.reason }}
        </div>
        <div class="form-group">
            <p class="text-left">ประเภท</p>
            {{ form.type }}
        </div>
        <div class="form-group">
            <p class="text-left">ตั้งแต่วันที่</p>
            {{ form.date_start }}
        </div>
        <div class="form-group">
            <p class="text-left">ถึงวันที่</p>
            {{ form.date_end }}
        </div>

        <div class="center group">
            <input class="btn btn-success" type="submit" value="Submit" />
            <a href="{% url 'index' %}">
                <input class="btn btn-danger" type="button" value="Back" />
            </a>
        </div>
    </form>
</div>
<style>
    .center {
        text-align: center;
    }
</style>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

dayoff/templates/dayoff/index.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Day Off</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
</head>
<body>
<div class="container">
    <div class="center title">
        <h1>Day Off System</h1>
        <h2>รานการคำขอลางานของฉัน</h2>
    </div>

    {% if user.is_authenticated %}
        <div class="">
            <table class="table">
                <tr>
                    <th>ประเภท</th>
                    <th>สาเหตุ</th>
                    <th>ตั้งแต่วันที่</th>
                    <th>ถึงวันที่</th>
                    <th>สถานะ</th>
                </tr>
                {% for dayoff in dayoff_list %}
                    <tr>
                        <td>
                            {% if dayoff.type == '01' %}
                                ลากิจ
                            {% elif dayoff.type == '02' %}
                                ลาป่วย
                            {% endif %}
                        </td>
                        <td>
                            {{ dayoff.reason }}
                        </td>
                        <td>
                            {{ dayoff.date_start }}
                        </td>
                        <td>
                            {{ dayoff.date_end }}
                        </td>
                        <td>
                            {% if dayoff.approve_status == 0 %}
                                <span class="badge badge-danger">ไม่อนุมัติ</span>
                            {% elif dayoff.approve_status == 1 %}
                                <span class="badge badge-success">อนุมัติ</span>
                            {% elif dayoff.approve_status == 2 %}
                                <span class="badge badge-secondary">รอการอนุมัติ</span>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% else %}
        <div class="alert alert-primary center narrow">
            กรุณาเข้าสู่ระบบเพื่อดูรายการคำขอลางาน.
        </div>
    {% endif %}

    <div class="center">
        <p class="text-muted">
            {% if user.is_authenticated %}
                <br>Logged in as {{ user.get_username }}
            {% endif %}
        </p>

        <!-- Create New Day Off -->
{#        https://docs.djangoproject.com/en/dev/ref/contrib/admin/#reversing-admin-urls#}
        {% if perms.dayoff.change_dayoff %}
            <a href="{% url 'admin:dayoff_dayoff_changelist' %}"
            ><button class="btn btn-secondary">Manager Panel</button></a
            >
        {% endif %}

        <!-- Create New Day Off -->
        {% if perms.dayoff.add_dayoff %}
            <a href="{% url 'create-dayoff' %}"
            ><button class="btn btn-success">Request Day Off</button></a
            >
        {% endif %}

        <!-- Login/Logout Button -->
        {% if not user.is_authenticated %}
            <a href="{% url 'login' %}"
            ><button class="btn btn-success">Login</button></a
            >
        {% else %}
            <a href="{% url 'logout' %}"
            ><button class="btn btn-danger">Logout</button></a
            >
        {% endif %}
    </div>
</div>

<style>
    .center {
        text-align: center;
    }
</style>
<script src="https://cdn.jsdelivr.net/npm/vue"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>